### ISSUE TITLE
Missing Senate votes

### ISSUE THREAD

**Issue by johnymontana** [legis-graph/legis-graph#1]

**Comment by ctembreull** [comment]
Would require tracking each vote taken - there are a lot, actually. Not a bad idea at all, but complex - not all votes map to bills.

**Comment by johnymontana** [comment]
Sorry, should have clarified I was only specifically interested in Senate votes on Bills (and specifically only role call votes).

We were importing House votes on Bills correctly but there was a bug that resulted in Senate votes not being imported, however this was resolved in 26933626d31c3624e07f304fd1c2514a49cc3644
