### ISSUE TITLE
Add note to install requirements

### ISSUE THREAD

**Issue by gregoryfoster** [legis-graph/legis-graph#6]
Speaking as a relative Python newb and `virtualenv` user, it could be helpful to add a note to the `README.md` to install the project's requirements:

```bash
pip3 install -r requirements.txt
```

I'd be happy to update the document and issue a pull request, just assign this issue to me.

**Comment by johnymontana** [comment]
Good point! 

Please feel free to submit a PR for this.

I think the only dependency is `pyyaml` as specified [here](https://github.com/legis-graph/legis-graph/blob/master/requirements.txt), but I might have missed others.

Thanks!

**Comment by johnymontana** [comment]
Fixed in #8
